### ISSUE TITLE
Uncaught TypeError: Cannot read property 'date' of undefined

### ISSUE THREAD

**Issue by Ayymoss** [rabidgremlin/auto-speedtest#3]
```
(index):128 Uncaught TypeError: Cannot read property 'date' of undefined
    at (index):128
    at Object.<anonymous> (d3.v3.js:1996)
    at Object.event (d3.v3.js:504)
    at XMLHttpRequest.respond (d3.v3.js:1949)
```

I've tried looking around to fix it, but I'm too stupid and don't know much about coding.
The capture script is working as intended, changed a few things but your index page doesn't seem to work anymore, sure it's been 3 years.

I was hoping maybe you'd look at fixing it? Maybe, maybe not. 

Cheers!

**Comment by rabidgremlin** [comment]
Wow, I'd forgotten I'd even put this together :)

I'll see if I can get it fixed up...

**Comment by Ayymoss** [comment]
Nice! I really appreciate you taking the time to look at your 3-year-old repo! :D

**Comment by rabidgremlin** [comment]
Ok found the issue. The scripts were not writing out the headers for the .CSV file so it wasn't  getting loaded by the webpage correctly. Have tweaked the `capture.sh` script.

However I also took the opportunity to clean things up and containerize the tool using Docker. Will make it much easier to get up and running. See the `README.md`` for more info.

Let me know if this works for you.

**Comment by Ayymoss** [comment]
Okay cool. I've tested it and it's working as previously intended! :)

Thanks for looking back at this project haha! +1

**Comment by rabidgremlin** [comment]
No problem. Was fun to dust this off :)
